### PR TITLE
fix(ng-model): Do not set value to an outdated value

### LINKED ISSUE #58: [Angular] Code disappears when editor has been loaded before
I faced with a problem of disappearing code in the editor.

**First thing first:**
Editor package version: `2.0.2`
Angular version: `7.1.3`

**Editor component usage in my component**
```
<td-code-editor style="height: 400px;" theme="vs-dark" language="javascript" formControlName="script"></td-code-editor>
```
As you can see above I use reactive forms.

Form's data are set using `patchValue` method after they are retrieved from the API. It's done asynchronously.
```javascript
this._deviceApiService.fetchDeviceScriptById(scriptId)
  .subscribe((script: DeviceScript) => {
    this.script = script;
    this.form.patchValue(script);
  });
```

### Observations
This happens when editor has been loaded before already, e.g. you go from page A to editor page for the first time and it works. Also when you visit editor page directly from URL or refresh page it's working.
But when you go back to page A and then again to editor page, then issue with disappearing code happens.

If I delay patching form value, then it's working in both cases (switching between pages or accessing directly via URL).
```javascript
setTimeout(() => this.form.patchValue(script), 500);
```

### PR DESCRIPTION
**Pull request by christianmemije**
Clears timeouts to prevent the `value` from being set to an outdated value. Fixes #58

#### TODOs

- Add unit tests

#### Test Steps

- [ ] `npm install`
- [ ] `npm run serve`
- [ ] `npm run lint`
- [ ] `npm test`
- [ ] `npm run build`
- [ ] `npm pack ./deploy/platform/code-editor/`
- [ ] Within app_center `npm install PATH_TO_TGZ_GENERATED`

### CODE REVIEW

File: src/platform/code-editor/code-editor.component.ts [hunk 1]
```diff
@@ -144,6 +144,10 @@ export class TdCodeEditorComponent implements OnInit, AfterViewInit, ControlValu
               }, 500);
             }
         }
+    } else {
```
Comment (christianmemije) [inline src/platform/code-editor/code-editor.component.ts:148]: If component isn't initialized yet, we should set a timeout

File: src/platform/code-editor/code-editor.component.ts [hunk 2]
```diff
@@ -155,7 +159,11 @@ export class TdCodeEditorComponent implements OnInit, AfterViewInit, ControlValu
    * Implemented as part of ControlValueAccessor.
    */
   writeValue(value: any): void {
-    this.value = value;
+    // do not write if null or undefined
+    // tslint:disable-next-line
+    if ( value != undefined) {
```
Comment (christianmemije) [inline src/platform/code-editor/code-editor.component.ts:165]: Safety check

File: src/platform/code-editor/code-editor.component.ts [hunk 3]
```diff
@@ -606,14 +614,14 @@ export class TdCodeEditorComponent implements OnInit, AfterViewInit, ControlValu
         this._webview.addEventListener('ipc-message', (event: any) => {
             if (event.channel === 'editorContent') {
               this._fromEditor = true;
-              this.writeValue(event.args[0]);
```
Comment (christianmemije) [inline src/platform/code-editor/code-editor.component.ts]: Do not write this value which always starts as an empty string?

File: src/platform/code-editor/code-editor.component.ts [hunk 4]
```diff
@@ -626,7 +634,6 @@ export class TdCodeEditorComponent implements OnInit, AfterViewInit, ControlValu
         // append the webview to the DOM
         this._editorContainer.nativeElement.appendChild(this._webview);
     }
-    this._componentInitialized = true;
```
Comment (christianmemije) [inline src/platform/code-editor/code-editor.component.ts:624]: Was set to true before the electron component emitted the `onEditorInitialized` event so moved where this is set to true.

**Review by jeremysmartt — APPROVED** [review]

**Review by JulieMarie — APPROVED** [review]
LGTM
